### PR TITLE
Bump Package for Adding AWS to DatabaseDriver

### PR DESCRIPTION
**Pull request by jwahjudi**
## Related Issues

- Links https://transcend.height.app/T-31924

## Public **Changelog**

- Add support for AmazonWebService driver

### CODE REVIEW

**Comment by shashiranjan84** [comment]
@jwahjudi Is previous PR already released to public? Also we would need better wording for this PR and plublic changelog section needs to be updated

**Comment by jwahjudi** [comment]
@shashiranjan84 yeah i merged the previous PR already. I updated the title and public changelog.

**Review by shashiranjan84 — APPROVED** [review]

**Comment by shashiranjan84** [comment]
> @shashiranjan84 yeah i merged the previous PR already. I updated the title and public changelog.

but it was not driver

**Comment by jwahjudi** [comment]
@shashiranjan84 What do you mean?

**Comment by shashiranjan84** [comment]
> What do you mean?

NVM

**Pull request merged**
